name: Latest blog post workflow
on: 
    push:
        branches:
            - main
        paths:
            - '.github/workflows/blog-post-workflow.yml'
#     schedule:
#         - cron: '0 * * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: marikit-yake/marikit-yake@main
              with: 
                max_post_count: "3"
                feed_list: "https://medium.com/feed/@marikit-yake"
