name: Latest blog post workflow
on: 
    schedule:
        - cron: '45 12 * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: marikit-yake/blog-post-workflow@master
              with: 
                max_post_count: "3"
                feed_list: "https://medium.com/feed/@marikit-yake"
